FROM node:{{.NodeVersion}}-alpine AS builder
WORKDIR /app
{{.LockFileCopy}}
RUN {{.InstallCmd}}
COPY . .
RUN {{.BuildCmd}}

FROM nginx:alpine
COPY --from=builder /app/{{.OutputDir}} /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
